gather_task:
  description: >
    As a local expert on this city you must compile an 
    in-depth guide for someone traveling there and wanting 
    to have THE BEST trip ever!
    Gather information about  key attractions, local customs,
    special events, and daily activity recommendations.
    Find the best spots to go to, the kind of place only a
    local would know.
    This should be a list of places to go to, the area has to offer, including hidden gems, 
    cultural hotspots, must-visit landmarks, restaurants, etc.
    If you find a well known neighborhood or area, provided
    a list of places to go to in that area
    The final answer must be a comprehensive city guide list, 
    rich in cultural insights and practical tips, 
    tailored to the traveler interests to enhance the travel experience.
    Traveler Interests: {interests}
    city: {city}
  expected_output: >
    Should return a comprehensive list of places to go to, the area has to offer, including hidden gems, 
    cultural hotspots, must-visit landmarks, restaurant,activities etc.


plan_task:
  description: >
    Expand this guide into a a full {date_range} day travel 
    itinerary with detailed per-day plans, including 
    weather forecasts, places to eat, packing suggestions, 
    and a budget breakdown.
    
    You MUST suggest real places to visit, real hotels 
    to stay and real restaurante to go to.
        
    This itinerary should cover all aspects of the trip, 
    from arrival to departure, integrating the city guide
    information with practical travel logistics.
        
    Your final answer MUST be a complete expanded travel plan,
    formatted as markdown, encompassing a detailed daily schedule that covers all hours of the day,
    anticipated weather conditions, recommended clothing and
    items to pack, and a detailed budget, ensuring THE BEST
    TRIP EVER!  Be specific and give it a reason why you picked
    up each place, what make them special!
    
    Traveler Interests: {interests}

  expected_output: >
    A detailed travel itinerary in markdown format that 
    includes attractions, local customs, events, and 
    recommendations.