gather_task:
  description: >
    As a local expert on this city you must compile an 
    in-depth guide for someone traveling there and wanting 
    to have THE BEST trip ever!
    Gather information about  key attractions, local customs,
    special events, and daily activity recommendations.
    Find the best spots to go to, the kind of place only a
    local would know.
    This should be a list of places to go to, the city has to offer, including hidden gems, 
    cultural hotspots, must-visit landmarks, restaurants, etc.
    
    The final answer must be a comprehensive city guide, 
    rich in cultural insights and practical tips, 
    tailored to enhance the travel experience.
    Traveler Interests: {interests}
    city: {city}
  expected_output: >
    A comprehensive city guide list that 
    includes attractions, local gems, events, and 
    recommendations.


plan_task:
  description: >
    Expand this guide into a a full {date_range} day travel 
    itinerary with detailed per-day plans, including 
    weather forecasts, places to eat, packing suggestions, 
    and a budget breakdown.
    
    You MUST suggest actual places to visit, actual hotels 
    to stay and actual restaurante to go to.
        
    This itinerary should cover all aspects of the trip, 
    from arrival to departure, integrating the city guide
    information with practical travel logistics.
        
    Your final answer MUST be a complete expanded travel plan,
    formatted as markdown, encompassing a daily schedule,
    anticipated weather conditions, recommended clothing and
    items to pack, and a detailed budget, ensuring THE BEST
    TRIP EVER, Be specific and give it a reason why you picked
    up each place, what make them special!
    
    Traveler Interests: {interests}

  expected_output: >
    A detailed travel itinerary in markdown format that 
    includes attractions, local customs, events, and 
    recommendations.