[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "chainlit>=2.2.0",
    "tripcrew",
]

[tool.uv.sources]
tripcrew = { workspace = true }
